### PR TITLE
Remove head hydration workaround

### LINKED ISSUE #1066: Remove head hydration workaround
**Is your feature request related to a problem? Please describe.**
Since Svelte 3.17.3 hydration now works with `head` elements. This removes the need for the `noscript` workaround.

**Describe the solution you'd like**
I will open PRs for `sapper` (sveltejs/sapper#1067) and `sapper-template` (sveltejs/sapper-template#195)

**Describe alternatives you've considered**
Use the workaround in perpetuity since it works now and probably forever.

**How important is this feature to you?**
Not very; it is just a minor cleanup for the next time breaking changes to Sapper are up for consideration.

**Additional context**
- sveltejs/svelte#1607
- sveltejs/svelte#4082
- sveltejs/svelte#4250
- sveltejs/svelte#4311

### PR DESCRIPTION
**Pull request by johnmuhl**
Closes #1066

### CODE REVIEW

**Comment by benmccann** [comment]
@johnmuhl should this also update the `package.json` to set svelte 3.17.3 as the minimum version required?

**Comment by Conduitry** [comment]
I'm taking a look at this again now that we're committed to the next release containing breaking changes - and I'm bothered that removing this isn't breaking any tests, even though we aren't updating any of the tests to include `hydratable: true` in the bundler's compiler config.

**Comment by benmccann** [comment]
Every test already has `hydratable: true` in its `rollup.config.js` file, so I think that's to be expected

**Comment by Conduitry** [comment]
The version of Svelte used in the tests in this branch is ancient though - https://github.com/sveltejs/sapper/blob/fcdd67be73b5ff9eb67ad57251952af8db1e8024/package-lock.json#L5312 - much older than the feature that this change relies on, which leads me to think this isn't being tested at all.

**Comment by benmccann** [comment]
Yeah, there's just one test for hydration and it does't test the `head` element: https://github.com/sveltejs/sapper/blob/a5a421f4b689eb6030db592f6dc85178d5c05d68/test/apps/basics/test.ts#L170

Do we need to add a new test for it though? Svelte should have tests for `head` hydration and I'm not sure if we're doing anything special once the workaround is removed

**Comment by Conduitry** [comment]
The `pkg.peerDependencies` should at least be updated to reflect the new requirement. This probably doesn't need to be called out in the migration section in the docs. I guess I'm okay without a test for this, since Svelte should be already testing it.

**Comment by benmccann** [comment]
Ok, I just bumped the `peerDependencies`, so I'll go ahead and merge this one

**Pull request merged**
