### PR TITLE
[Docs] add note about installing Cypress

### PR DESCRIPTION
**Pull request by rdela**
...to `content/docs/14-testing.md`

See
- <https://github.com/sveltejs/sapper-template/issues/22#issuecomment-500228964>
- <https://github.com/sveltejs/sapper-template/issues/177#issuecomment-548165305>

### CODE REVIEW

**Comment by rdela** [comment]
> I think this could be formatted better, a new paragraph perhaps, to explain the commands.

Not sure what you mean by this, could you try to be more specific?

**Comment by rdela** [comment]
Clarified note and split into 3 paragraphs, and expanded the command (`npm i -D` => `npm install --save-dev`) per discussion in https://github.com/sveltejs/sapper-template/pull/194

@antony was this what you had in mind?

**Comment by benmccann** [comment]
Related: https://github.com/sveltejs/sapper-template/pull/194

**Comment by thgh** [comment]
I would not recommend to add Cypress by default, it slows down the default install significantly and is probably not used that often.

How about adding a cypress command that just tells (or lets) you to install the real cypress?

**Comment by benmccann** [comment]
> I would not recommend to add Cypress by default, it slows down the default install significantly and is probably not used that often.

I think if it's not used that often we should just remove it. It seems too opinionated to be in the default template to me. It's not a good fit for too many projects: if you need to support IE 11, need to test iframes or popups, use Jest, etc.

**Comment by rdela** [comment]
In the interest of incorporating as many points of view as possible, I agree with [Conduitry's comment](https://github.com/sveltejs/sapper-template/pull/227#issuecomment-632700810) on Ben's PR:

> Having the skeleton of a setup for Cypress without having Cypress as a devdep does seem bad, but adding Cypress as a devdep for everyone seems worse, because it is huge. I don't know what the right solution is here. We don't currently have a mechanism for generating different templates with different features toggled on and off, apart from the very simple Rollup vs webpack template thing.

I found the Cypress setup to be really informative and am using it on all my Sapper projects now. I agree with [Rich's 2017 assessment that it is the best way to test Sapper apps](https://github.com/sveltejs/sapper-template/issues/1#issue-282729139):

> Gleb Bahmutov was kind enough to write up his experience of using Cypress to test a Svelte app, and I think Cypress is probably the right go-to choice for testing Sapper apps.

It was crucial to getting GitLab CI to work when I was building my [Sapper GitLab Pages Markdown example](https://rdela.gitlab.io/sapper-v3/). The only stumbling block for me was having to install it and the lack of documentation around that. If we could get this PR and https://github.com/sveltejs/sapper-template/pull/194 merged then the lack of documentation problem would be solved at least.

**Comment by benmccann** [comment]
Cypress was removed from the template in https://github.com/sveltejs/sapper-template/pull/263

**Pull request closed without merging**
