### PR TITLE
Waiting for all requests to finish before closing q.

### PR DESCRIPTION
**Pull request by btakita**
Fixes issues/689

`await Promise.all(promises)`

### CODE REVIEW

**Comment by mrkishi** [comment]
How does this relate to #604 and #641?

It looks good at first glance, but does it reintroduce #604's problem?

**Comment by btakita** [comment]
Should we introduce rate limiting?

**Comment by btakita** [comment]
https://github.com/sveltejs/sapper/pull/690/commits/d3fc0c1eae312a6a05464a175b9126ff8bdc9e61 adds rate limiting based on the `concurrent` option. The default is 8.

**Comment by btakita** [comment]
I took another look & realized I was missing a big part of the picture.

Here's how I see the situation. This PR fixes https://github.com/sveltejs/sapper/issues/689 which is caused by `handle` not waiting for all requests to finish.

The `await Promise.all`simply waits for all of the requests to finish. There is some rate limiting by chunking calls to `handle`, however this does not guarantee the limit to be `concurrent` due to this solution not being a proper queue.

`q.add` should be the solution, however removing `q.add` was the fix for https://github.com/sveltejs/sapper/issues/604 & https://github.com/sveltejs/sapper/issues/641.

Does this mean there's a bug with the queue? If so, then the bug with queue should be fixed, since the queue is needed to guarantee a concurrent request limit of `concurrent`.

**Comment by btakita** [comment]
@mrkishi To answer your question, this PR has no effect on https://github.com/sveltejs/sapper/issues/604 or https://github.com/sveltejs/sapper/issues/641.

The only way this would reintroduce https://github.com/sveltejs/sapper/issues/604 is if the `UnhandledPromiseRejectionWarning: Error: Cannot add to a closed queue` "fixes" the issue by limiting the number of requests.

**Comment by mrkishi** [comment]
Hey, @btakita. It's not that I disagree that there's a problem, it's just that the root of the issue theoretically _shouldn't_ be awaiting those promises, since `handle` is supposed to use `queue` and thus guaranteed to finish sequentially.

I tried another fix that shouldn't ignore promises in case of timeouts at #698. Could you test that version to verify if it solves your problem? I don't have a codebase where #689 happens and I'm not sure what's required to create a test (if you do, we should add a test!).

**Comment by mrkishi** [comment]
Err, I seem to have misunderstood everything. Indeed we should be waiting for all `handle`s since the `q` is only happening for `fetch`. In any case, the `q` should enclose the whole request or else timeouts would break.

**Comment by btakita** [comment]
I tested your branch with the `dist` & `runtime` files `"sapper": "btakita/sapper#gh-689"` & the issue is fixed.

**Comment by btakita** [comment]
I agree that the queue should be used to manage all of the tasks. Well done!

**Comment by Rich-Harris** [comment]
Closing in favour of #698 — will cut a release soon

**Pull request closed without merging**
