### PR TITLE
Adds example to goto documentation

### PR DESCRIPTION
**Pull request by kevmodrome**
I was a bit confused as to where I would import goto from so I added a small usage example.

### CODE REVIEW

**Comment by Conduitry** [comment]
Maybe an example with `await` to indicate that this navigation is not synchronous, and that you can use the promise to deal with that,

**Comment by kevmodrome** [comment]
I changed the example a bit and added a sentence to the promise documentation. I'm not sure how elaborate of an example is warranted. Should I do one that does something both on resolve as well as reject or is this fine?

**Comment by Conduitry** [comment]
I went to push a couple of tweaks before squashing merging this, but apparently you didn't enable allowing maintainers to push to the branch this PR is from.

**Comment by kevmodrome** [comment]
My bad @Conduitry, enabled it.

**Pull request merged**
