### PR TITLE
Upgrade rollup-plugin-css-chunks

### PR DESCRIPTION
**Pull request by benmccann**
Fixes https://github.com/sveltejs/sapper/issues/1564

This is a breaking change, so the next release would have to be Sapper 0.29.0. See https://github.com/domingues/rollup-plugin-css-chunks/pull/17

### CODE REVIEW

**Comment by Conduitry** [comment]
Is this pending the merge and release of https://github.com/domingues/rollup-plugin-css-chunks/pull/17 ? Would that then be version 3 of that plugin? Or was version 2 the breaking change, and that PR is just fixing the peerdep ranges to match what it already requires?

**Comment by benmccann** [comment]
Version 2 was the breaking change and that PR is just fixing the `peerDependencies`

**Comment by benmccann** [comment]
@Conduitry are you okay if I merge this and we make the next release 0.29 with this breaking change? I'd like to get some more eyes on the new version of the css plugin since it's used by SvelteKit as well

**Comment by Conduitry** [comment]
I'm fine with this change, but are there other breaking changes we should get cued up for a new version?

**Comment by benmccann** [comment]
There were a few other breaking changes I was originally considering before SvelteKit came along: https://github.com/sveltejs/sapper/issues/1545.
There's no PR available for the `segment` prop change, so I'm not sure that's something that would get done.
Reverting #1244 and merging #1566 probably make sense though

**Pull request merged**
