### PR TITLE
[...spread] routes

### PR DESCRIPTION
**Pull request by cudr**
implement #545

### CODE REVIEW

**Comment by cudr** [comment]
Important notice: changes in the comparator function only work on node 11 and above, see https://github.com/nodejs/node/issues/24294

**Comment by Rich-Harris** [comment]
Thanks @cudr, this is great news — though I'm not sure I understand the comment about the comparator function. Are you saying Sapper's behaviour would differ between Node 10 and 11 with this PR?

**Comment by cudr** [comment]
@Rich-Harris Yes, there was some uncertainty due to which the comparator function behaved differently between 10 and 11. Now more tests are added and it works the same way on both 10 and 11 versions of the nodejs

**Comment by Rich-Harris** [comment]
awesome, thanks

**Pull request merged**
