### PR TITLE
Make <base> optional

### LINKED ISSUE #904: make sapper.base optional
**Is your feature request related to a problem? Please describe.**
sapper.base was introduced to solve https://github.com/sveltejs/sapper/issues/180 over a year ago. it is not optional for sapper to compile (i'm not sure why, but im sure there are good reasons). however, this causes screwy things to happen for relative/anchor links.

in discord, rich has voiced willingness:

>  unindented03/15/2019
> is there a way to avoid including %sapper.base% and have prefetching still work? that <base> tag is making me really unhappy
it means I can't have relative links anywhere
it also fucks up my anchor links
 
> rich_harris03/15/2019
> not in the current version. would love to get rid of it, it needs some care though

**Describe the solution you'd like**
make `<base>` be optional, if not supplied by the user.

**Describe alternatives you've considered**
none

**How important is this feature to you?**
moderate. i'm autogenerating some links and having to account for base is making it pretty tricky.

### PR DESCRIPTION
**Pull request by thgh**
Adds an option `baseTag: false` to sapper.middleware to opt out of the `<base>` tag

Resolves #904 => issues with svg and css `url()`
Base tag was introduced in #180

Could perhaps be extended to support #866 (I have not checked effect on sapper export)
Could also be extended to support #600 (By adding a baseOrigin option)

### CODE REVIEW

**Comment by benmccann** [comment]
@thgh I think this PR will end up being blocked until we figure out how to handle configuration in Sapper. [I raised an RFC](https://github.com/sveltejs/rfcs/pull/23) since I'm also blocked by that decision. Please take a look and feel free to leave any feedback there

**Comment by benmccann** [comment]
It was reported in https://github.com/sveltejs/sapper/pull/1237 that export won't work if `base` is not present. I haven't tested myself, but assuming that's true than I imagine this will break export

**Comment by thgh** [comment]
Looks like export only supports `base` indeed, that should be easily fixed by using [this `url`](https://github.com/akvadrako/sapper/blob/55ba30b6ceb6d8dec1e713046ff6ad48c94a2e25/src/api/export.ts#L154) as `base`.

**Comment by benmccann** [comment]
https://github.com/sveltejs/sapper/pull/1208 is trying to solve the export problem, so I think if it gets merged first then it will be fine

**Comment by benmccann** [comment]
Thanks for putting together this PR! Sapper never had a good method of handling configuration, which made it difficult to know how to integrate this feature. However, that's been addressed in SvelteKit which has a `svelte.config.cjs` file. I'm going to go ahead and close this PR since we won't be adding the feature to Sapper, but if you'd like to check out SvelteKit we will be reviewing PRs for features there

**Pull request closed without merging**
