### PR TITLE
Wait upto 30 seconds for server ready

### PR DESCRIPTION
**Pull request by thgh**
Resolves sveltejs/sapper#730

Related: #1007

### CODE REVIEW

**Comment by benmccann** [comment]
@thgh thanks for this. I think it might be the same as https://github.com/sveltejs/sapper/pull/1239 which was recently merged?

**Comment by benmccann** [comment]
Could we do `ports.wait(this.port, { timeout: 30000 })` instead? It looks to me like you can from the [port-authority README](https://github.com/Rich-Harris/port-authority/) though I'm not 100% sure. If not, I think making that configurable in `port-authority` first would be cleaner than trying to work around it here

**Comment by thgh** [comment]
I like seeing that some process is taking longer than expected, I think in this case it informs the user something's up with their underlying system. Too bad it's not very actionable, but I haven't seen an actual solution so not sure if there is a more helpful message.

**Comment by benmccann** [comment]
Sorry this had gone unreviewed for so long. It looks like there's a merge conflict here. Maybe it's better to try to make sure SvelteKit works as desired than trying to get it in here at this point?

**Comment by thgh** [comment]
Sure!

**Comment by benmccann** [comment]
Thanks!

**Pull request closed without merging**
