### PR TITLE
Update 02-routing.md

### PR DESCRIPTION
**Pull request by salvatoredangelo**
I wish I was strong enough to ignore it, but can I get that "s" please?

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR relates to an outstanding issue, so please reference it in your PR, or create an explanatory one for discussion. In many cases features are absent for a reason.
- [x] This message body should clearly illustrate what problems it solves. If there are related issues, remember to reference them.
- [x] Ideally, include a test that fails without this PR but passes with it. PRs will only be merged once they pass CI. (Remember to `npm run lint`!)
### Tests
-  [x] Run the tests tests with `npm test` or `yarn test`)

### CODE REVIEW

**Comment by salvatoredangelo** [comment]
Just a simple typo yall

**Comment by antony** [comment]
I would counter that "route" is an uncountable noun. Route here refers to a general concept, not something that can be counted.

Uncountable nouns are always singular.

**Comment by salvatoredangelo** [comment]
perhaps a bit cutsy, but I can see the light on this, cheers

**Comment by benmccann** [comment]
I'm not quite sure why routes are uncountable. There's always a discrete integer number of routes. Personally, "route" sounds extremely wrong too me

**Comment by antony** [comment]
Because route here refers to the concept of routes not the actual routes themselves.

**Comment by Conduitry** [comment]
I am not sure sure I'd say that "route" is an uncountable noun, but I would say that "two types of route" sounds a bit British and not American to me, which honestly is fine and acceptable and expected and desirable given the author.

**Comment by benmccann** [comment]
Ah, yeah, it could be a Britishism I'm unfamiliar with

**Pull request closed without merging**
